// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6w0IXIj1BG3rOvja4ELmMSa-u1JOIEL4',
    appId: '1:121269795957:web:68a51dc70a555d91b00c3c',
    messagingSenderId: '121269795957',
    projectId: 'find-cabs',
    authDomain: 'find-cabs.firebaseapp.com',
    databaseURL: 'https://find-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'find-cabs.appspot.com',
    measurementId: 'G-DVDH1XVLBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0I-BTc8kTxl6GDSS6ERhKyDVGbWKe4A',
    appId: '1:44078972937:android:acb3744c12868c658e78d8',
    messagingSenderId: '44078972937',
    projectId: 'sampark-f6b6c',
    storageBucket: 'sampark-f6b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU7XHTNjgdlP6oXy6Vt7n9kIcWMqeQPZA',
    appId: '1:121269795957:ios:38f4b09abcd783f6b00c3c',
    messagingSenderId: '121269795957',
    projectId: 'find-cabs',
    databaseURL: 'https://find-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'find-cabs.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}